In [1]:
#Define a string with a value equal to “Python is fun!”. Print every third character of this string
s = 'Python is fun!'
print(s[::3])

Ph  n


In [24]:
#Create three list variables named 'StudentName', 'ID', and 'EmailAddress'. 

StudentNames = []
ID = []
EmailAddress = []

#Add 5 random values in these lists and print them.
import random
from random import randint

first_names = ['Alex', 'Martin', 'David', 'Jennifer', 'Kate', 'Joe', 'Josh', 'Peter', 'Jack', 'Ella', 'Lily']
last_names = ['Smith', 'Oldman', 'Lawrence','Tan','Lacroix', 'Ng', 'Nguyen', 'Bryan', 'Moss']



for i in range(5):
    StudentNames.append(random.sample(first_names, 1)[0] + ' ' + random.sample(last_names , 1)[0])
    
for i in range(5):
    EmailAddress.append(StudentNames[i].replace(' ', '.').lower() + '@deakin.edu.au')
    
for i in range(5):
    ID.append(randint(100000, 999999))

    
print('Student Names: ', StudentNames)
print('ID: ', ID)
print('Email: ',EmailAddress)

Student Names:  ['Martin Lacroix', 'Jack Tan', 'Alex Moss', 'Kate Oldman', 'Ella Lacroix']
ID:  [376887, 586579, 173876, 509469, 946356]
Email:  ['martin.lacroix@deakin.edu.au', 'jack.tan@deakin.edu.au', 'alex.moss@deakin.edu.au', 'kate.oldman@deakin.edu.au', 'ella.lacroix@deakin.edu.au']


In [25]:
#Create a dictionary variable with three keys, which are named same as the list created in the previous problem.
#Insert the previously created lists in the dictionary variable and print it.

data = {'StudentNames': StudentNames,
       'ID': ID,
       'EmailAddress': EmailAddress }
data

{'StudentNames': ['Martin Lacroix',
  'Jack Tan',
  'Alex Moss',
  'Kate Oldman',
  'Ella Lacroix'],
 'ID': [376887, 586579, 173876, 509469, 946356],
 'EmailAddress': ['martin.lacroix@deakin.edu.au',
  'jack.tan@deakin.edu.au',
  'alex.moss@deakin.edu.au',
  'kate.oldman@deakin.edu.au',
  'ella.lacroix@deakin.edu.au']}

In [40]:
#Define a numeric variable 'energy' and assign value either 1 or 2.
energy = randint(1, 10)

#Print "Apple" if the value of energy variable is 1 otherwise print "Banana".
def printS (energy):
    if energy == 1:
        print('Apple')
    elif energy==2:
        print('Banana')
    else:
        print ('Energy not valid')
printS(energy)

Apple


* **What will your program print if energy=10**

If the energy is 10, the function will print an exception

In [23]:
#Print numbers between 0 and 2000 separated by line, which are divisible by 5.
for i in range(0,2001):
    if i%5 == 0:
        print(i)

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
105
110
115
120
125
130
135
140
145
150
155
160
165
170
175
180
185
190
195
200
205
210
215
220
225
230
235
240
245
250
255
260
265
270
275
280
285
290
295
300
305
310
315
320
325
330
335
340
345
350
355
360
365
370
375
380
385
390
395
400
405
410
415
420
425
430
435
440
445
450
455
460
465
470
475
480
485
490
495
500
505
510
515
520
525
530
535
540
545
550
555
560
565
570
575
580
585
590
595
600
605
610
615
620
625
630
635
640
645
650
655
660
665
670
675
680
685
690
695
700
705
710
715
720
725
730
735
740
745
750
755
760
765
770
775
780
785
790
795
800
805
810
815
820
825
830
835
840
845
850
855
860
865
870
875
880
885
890
895
900
905
910
915
920
925
930
935
940
945
950
955
960
965
970
975
980
985
990
995
1000
1005
1010
1015
1020
1025
1030
1035
1040
1045
1050
1055
1060
1065
1070
1075
1080
1085
1090
1095
1100
1105
1110
1115
1120
1125
1130
1135
1140
1145
1150
1155
1160
1165
1170
1175
1180
1185
1190
1195
1200
1205
1210
1215
12

* **Is it possible to break a loop before executing for the defined number of iterations?**


Yes, it is

* **If yes, provide an example using While loop structure.**



In [2]:
for i in range (5):
    if i == 3:
        break
    print(i)

0
1
2


In [48]:
#Create a function with two input parameters say (x, y) 
#and return output values by doing operations such as 'x+y' and 'x-y'. 
#Call the function with (4,7) and print the outputs.

def function(x, y):
    add = x + y
    minus = x - y
    print('Add: ', add)
    print('Minus: ', minus)

function(4,7)

Add:  11
Minus:  -3


In [50]:
#Create and display a 3X3 Identity matrix and multiply it with a 3x4 Random matrix.

import numpy as np

iMatrix = np.identity(3, dtype = float)
randMatrix = np.random.rand(3,4)

result = np.dot(iMatrix,randMatrix)
result

array([[0.90969895, 0.31772757, 0.61701597, 0.40082889],
       [0.66985335, 0.72245896, 0.004404  , 0.36538185],
       [0.97120133, 0.54997134, 0.39411593, 0.6880837 ]])

In [59]:
#Create a 5x2 matrix, initialise with random values and print it. 
#Now, transpose the matrix and print it. How the transposed matrix is different from original matrix? 
original_matrix = np.random.rand(5,2)
print('Original Matrix: \n',original_matrix)
transpose_matrix = np.transpose(original_matrix)
print('Transposed Matrix: \n', transpose_matrix)

print('Original size: ', np.shape(original_matrix))
print('Transpose size: ', np.shape(transpose_matrix))

Original Matrix: 
 [[0.01348289 0.91401518]
 [0.5017694  0.97789634]
 [0.01195553 0.68604769]
 [0.54341081 0.52528136]
 [0.07519908 0.91969573]]
Transposed Matrix: 
 [[0.01348289 0.5017694  0.01195553 0.54341081 0.07519908]
 [0.91401518 0.97789634 0.68604769 0.52528136 0.91969573]]
Original size:  (5, 2)
Transpose size:  (2, 5)


(2, 5)

* **Read the data stored in the "data.csv" file as a matrix. The row of the matrix represents data point or instance and the column represents the variable or feature. Print the number of data instances and variables present in this dataset. Calculate mean of the second variable and deduct this mean from original values of the variable. Print both original and modified values of the variable.**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv('data.csv', names=['feature1', 'feature2'], index_col=False)

In [15]:
df.head()

feature1  feature2
0    3.3816    3.3891
1    4.5279    5.8542
2    2.6557    4.4120
3    2.7652    3.7154
4    2.8466    4.1755

In [18]:
df.shape

(50, 2)

*The data set has 50 rows and 2 columns*

In [12]:
#Calculate the mean of the second variable
mean = df['feature2'].mean()
mean

5.002806

In [19]:
#Subtract the original values by the by calculated
new_df = df.copy()
new_df['feature2']=new_df['feature2']-mean
new_df.head()

feature1  feature2
0    3.3816 -1.613706
1    4.5279  0.851394
2    2.6557 -0.590806
3    2.7652 -1.287406
4    2.8466 -0.827306